### ISSUE TITLE
YouTube reporting fails when using SQLite and time zone set to US/Mountain

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#1111]
Note if we use MySQL - NO such error exists. Anyway, the PDF ends with the error:
```
2019-03-13 02:31:00,822 time data '2019-03-13T00:31:22-06:00' does not match format '%Y-%m-%dT%H:%M:%SZ'
2019-03-13 02:31:00,834 Traceback (most recent call last):
  File "/opt/websafety/var/console/traffic/pdf/pdf_generator.py", line 108, in generate_pdf_report
    reports[meta["template"]].build()
  File "/opt/websafety/var/console/traffic/pdf/base_report.py", line 65, in build
    self.build_content(report)
  File "/opt/websafety/var/console/traffic/pdf/youtube_report.py", line 23, in build_content
    stamp = datetime.datetime.strptime(video["timestamp"], "%Y-%m-%dT%H:%M:%SZ")
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019-03-13T00:31:22-06:00' does not match format '%Y-%m-%dT%H:%M:%SZ'


```

**Comment by ra-at-diladele-com** [comment]
Fixed in 7.2 by completely rewritten reporting.
