### ISSUE TITLE
Shall we continue the collector after errors?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#1438]
```
2020-03-01 16:19:15,370 	/var/log/squid/access.log.3.gz: 111424 lines, 0 errors, time 00:00:11
2020-03-01 16:19:15,370 	/opt/websafety/var/cluster/logs/192.168.4.12/access.log.3.gz.bak: 3.4 Mb size
Traceback (most recent call last):
  File "/opt/websafety-ui/bin/collector.py", line 88, in <module>
    main()
  File "/opt/websafety-ui/bin/collector.py", line 84, in main
    run(args)
  File "/opt/websafety-ui/bin/collector.py", line 38, in run
    collector.collect()
  File "/opt/websafety-ui/bin/daemon/stats/collector/collector_cron.py", line 64, in collect
    self.collect_file(file)
  File "/opt/websafety-ui/bin/daemon/stats/collector/collector_cron.py", line 94, in collect_file
    line = reader.getline()
  File "/opt/websafety-ui/bin/daemon/stats/collector/reader.py", line 30, in getline
    line = self.fin.readline()
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
2020-03-01 16:19:16,573 Running Report Builder with the following parameters:
2020-03-01 16:19:16,573 	Logs folder: /var/log/squid
```

**Comment by ra-at-diladele-com** [comment]
For now we consider error while reading access log a complete PANIC. Will need to dig further and/or maybe allow some UI setting for that.

**Comment by ra-at-diladele-com** [comment]
Done, we now dump to log that this give GZIPPED access log was not readable, for example. And continue parsing the next log.
