### ISSUE TITLE
A broken access.log.gz prevents from collector from continuing...

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#1460]
We should catch the error and continue collecting the next file. An error in the log is ok for the admin to manually remove the broken GZ file.

```
2020-03-20 06:26:26,593 	/opt/websafety/var/cluster/logs/192.168.4.14/access.log.1.gz: 1.2 Mb size
Traceback (most recent call last):
  File "/opt/websafety-ui/bin/collector.py", line 77, in <module>
    main()
  File "/opt/websafety-ui/bin/collector.py", line 73, in main
    run(args)
  File "/opt/websafety-ui/bin/collector.py", line 40, in run
    collector.collect()
  File "/opt/websafety-ui/bin/daemon/stats/collector/collector_cron.py", line 89, in collect
    self.collect_file(file)
  File "/opt/websafety-ui/bin/daemon/stats/collector/collector_cron.py", line 125, in collect_file
    line = reader.getline()
  File "/opt/websafety-ui/bin/daemon/stats/collector/reader.py", line 30, in getline
    line = self.fin.readline()
  File "/usr/lib/python3.6/gzip.py", line 374, in readline
    return self._buffer.readline(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
```

**Comment by ra-at-diladele-com** [comment]
Added a try catch for a file collection, if file is broken it is skipped and collection will be re-tried next run.
