### ISSUE TITLE
Report generation fails on mixed stats with and without uploaded size?

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#1559]
```
2020-06-10 06:26:23,054 	build 2020-04 monthly report ...
Traceback (most recent call last):
  File "/opt/websafety-ui/bin/reporter.py", line 109, in <module>
    main()
  File "/opt/websafety-ui/bin/reporter.py", line 105, in main
    run(args)
  File "/opt/websafety-ui/bin/reporter.py", line 63, in run
    run_cron(config, args.force)
  File "/opt/websafety-ui/bin/reporter.py", line 30, in run_cron
    r.report(force)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/cron.py", line 46, in report
    m.report(force)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/month.py", line 61, in report
    self.generate_month(prefix, month, year)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/month.py", line 109, in generate_month
    r.build(folders)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/builders/_impl/periodic/builder.py", line 37, in build
    self.build_users(periods)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/builders/_impl/periodic/builder.py", line 42, in build_users
    users = UsersBuilder(self.folder).build(periods)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/builders/_impl/periodic/builder_items.py", line 37, in build
    view, totals = a.aggregate(df)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/builders/_impl/periodic/aggregators/users.py", line 14, in aggregate
    view   = self.calculate_view(df)
  File "/opt/websafety-ui/bin/daemon/stats/reporter/builders/_impl/periodic/aggregators/users.py", line 41, in calculate_view
    view["request_size_percent"]  = np.ceil(100 * view["request_size"] / view["request_size"].sum()).astype(int)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 5698, in astype
    new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 582, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 442, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/blocks.py", line 625, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/dtypes/cast.py", line 868, in astype_nansafe
    raise ValueError("Cannot convert non-finite values (NA or inf) to integer")
ValueError: Cannot convert non-finite values (NA or inf) to integer
2020-06-10 06:26:23,648 Running License Reporter with the following parameters:
```

**Comment by ra-at-diladele-com** [comment]
After installing a new version - in order to completely re-generate the statistics, consult the article at https://docs.diladele.com/administrator_guide_develop/traffic_monitoring/upgrades.html

**Comment by ra-at-diladele-com** [comment]
After installing a new version - in order to completely re-generate the statistics, consult the article at https://docs.diladele.com/administrator_guide_develop/traffic_monitoring/upgrades.html

**Comment by ra-at-diladele-com** [comment]
After installing a new version - in order to completely re-generate the statistics, consult the article at https://docs.diladele.com/administrator_guide_develop/traffic_monitoring/upgrades.html
