### ISSUE TITLE
eCAP crashing squid after Clam AV update (update high CPU usage)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#2012]
The only workaround for now is to disable eCAP.

**Comment by ra-at-diladele-com** [comment]
To reproduce - enable eCAP ClamAV engine and click Save and Restart in Admin UI. The squid will read the new configuration, and will run eCAP module at startup. eCAP module will try to load the clam av database and crash.

To debug it, in first terminal run ```systemctl  start squid``` command, this will start Squid process, and it will start initializing the ClamAV database, as it is a long process...

In second terminal, find out the PID of the Squid consuming a lot of CPU, I use ```htop```. Then attach the ```gdb -p NUMBER``` and allow it to run. It will then break into debugger upon crash. The ``bt`` shows:

```
#0  0x00007fab13a44ff0 in cli_bm_scanbuff () from /lib/x86_64-linux-gnu/libclamav.so.9
#1  0x00007fab13a4c8da in ?? () from /lib/x86_64-linux-gnu/libclamav.so.9
#2  0x00007fab13a52023 in ?? () from /lib/x86_64-linux-gnu/libclamav.so.9
#3  0x00007fab13a545a9 in ?? () from /lib/x86_64-linux-gnu/libclamav.so.9
#4  0x00007fab13a5a589 in ?? () from /lib/x86_64-linux-gnu/libclamav.so.9
#5  0x00007fab13a5b4cf in ?? () from /lib/x86_64-linux-gnu/libclamav.so.9
#6  0x00007fab13a54251 in ?? () from /lib/x86_64-linux-gnu/libclamav.so.9
#7  0x00007fab13a5767a in cl_load () from /lib/x86_64-linux-gnu/libclamav.so.9
#8  0x00007fab13c123e5 in Adapter::ClamAv::loadDatabase (this=this@entry=0x56119a5f4290) at ClamAv.cc:137
#9  0x00007fab13c12658 in Adapter::ClamAv::configure (this=0x56119a5f4290, cfg=...) at ClamAv.cc:83
#10 0x00007fab13c0939d in Adapter::Service::configure (this=0x56119a5ef940, cfg=warning: RTTI symbol not found for class 'Adaptation::Ecap::ConfigRep'
...) at /usr/include/c++/9/tr1/shared_ptr.h:668
#11 0x000056119979bd04 in Adaptation::Ecap::ServiceRep::tryConfigureAndStart() ()
#12 0x000056119979c38b in Adaptation::Ecap::ServiceRep::finalize() ()
#13 0x0000561199783126 in Adaptation::Config::Finalize(bool) ()
#14 0x000056119951ba3f in SquidMain(int, char**) ()
#15 0x00005611993a8ef6 in main ()
(gdb)
```

**Comment by ra-at-diladele-com** [comment]
Added a question at http://lists.squid-cache.org/pipermail/squid-users/2023-March/025675.html

**Comment by ra-at-diladele-com** [comment]
The issue seems to be resolved, at least now the AV starts normally and Squid continues to work ok.

**Comment by ra-at-diladele-com** [comment]
Now it seems the eCAP module that is loaded into Squid starts consuming a lot of RAM/CPU - but not crashing at least.
