### ISSUE TITLE
history reporter fails

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#2089]
```
root@node12:/opt/websafety-ui/var/reports/2023-08-11.temp# cat generation.log
2023-08-11 14:03:48,990 Report Builder is starting...
2023-08-11 14:03:49,330 Report Builder failed!
2023-08-11 14:03:49,330 Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
2023-08-11 14:03:49,333 Traceback (most recent call last):
  File "/opt/websafety-ui/bin/reporter_py/reporter.py", line 134, in main
    run(args)
  File "/opt/websafety-ui/bin/reporter_py/reporter.py", line 93, in run
    run_specific(args.out_dir, c)
  File "/opt/websafety-ui/bin/reporter_py/reporter.py", line 59, in run_specific
    r.build(config.frames)
  File "/opt/websafety-ui/bin/reporter_py/builders/specific/builder.py", line 40, in build
    self.build_hits(df)
  File "/opt/websafety-ui/bin/reporter_py/builders/specific/builder.py", line 105, in build_hits
    v = HitsPer10MinutesGenerator().generate(df)
  File "/opt/websafety-ui/bin/reporter_py/builders/specific/generators/hits.py", line 72, in generate
    resampled = df.resample('600s').sum()
  File "/opt/websafety-ui/env/lib/python3.8/site-packages/pandas/core/frame.py", line 10994, in resample
    return super().resample(
  File "/opt/websafety-ui/env/lib/python3.8/site-packages/pandas/core/generic.py", line 8888, in resample
    return get_resampler(
  File "/opt/websafety-ui/env/lib/python3.8/site-packages/pandas/core/resample.py", line 1523, in get_resampler
    return tg._get_resampler(obj, kind=kind)
  File "/opt/websafety-ui/env/lib/python3.8/site-packages/pandas/core/resample.py", line 1713, in _get_resampler
    raise TypeError(
TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

```

**Comment by ra-at-diladele-com** [comment]
it is because of incorrectly serialized value of exact localtime with 0 milliseconds in one of the logs - fixed and need to test

**Comment by ra-at-diladele-com** [comment]
working
