### ISSUE TITLE
on RHEL 9 the configuration/restore does not work as it uses PyOpenSSL

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#2097]
```


Warning!

Cannot restore configuration, errors: Command /usr/bin/sudo /opt/websafety-ui/bin/certmgr.py --action=regenerate-certificate-storage failed. Exit Code: 1 STDOUT: STDERR: Traceback (most recent call last): File "/opt/websafety-ui/bin/certmgr.py", line 11, in <module> import OpenSSL ModuleNotFoundError: No module named 'OpenSSL'

Traceback (most recent call last):
  File "/opt/websafety-ui/var/console/node/views/backup.py", line 119, in form_valid
    self.do_action(form)
  File "/opt/websafety-ui/var/console/node/views/backup.py", line 158, in do_action
    self.do_import(form, unpack_dir, hint)
  File "/opt/websafety-ui/var/console/node/views/backup.py", line 265, in do_import
    SquidCertDbInitializer().initialize()
  File "/opt/websafety-ui/var/console/_domain/squid/squid_cert.py", line 91, in initialize
    raise Exception(
Exception: Command /usr/bin/sudo /opt/websafety-ui/bin/certmgr.py --action=regenerate-certificate-storage failed.
	Exit Code: 1
	STDOUT: 
	STDERR: Traceback (most recent call last):
  File "/opt/websafety-ui/bin/certmgr.py", line 11, in <module>
    import OpenSSL
ModuleNotFoundError: No module named 'OpenSSL'


```

**Comment by ra-at-diladele-com** [comment]
fixed by adding `dnf install python3-pyOpenSSL`
