### ISSUE TITLE
Error with license and root ca notifiers after moving to C#

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#2173]
```
Traceback (most recent call last):
  File "/opt/websafety-ui/var/console/notify.py", line 37, in <module>
    from reporter_py.custom    import Mailer as SmtpMailer, ConfigMailer
ModuleNotFoundError: No module named 'reporter_py'
Traceback (most recent call last):
  File "/opt/websafety-ui/var/console/notify.py", line 37, in <module>
    from reporter_py.custom    import Mailer as SmtpMailer, ConfigMailer
ModuleNotFoundError: No module named 'reporter_py'
```

**Comment by ra-at-diladele-com** [comment]
in /etc/cron.daily/websafety_report

**Comment by ra-at-diladele-com** [comment]
Decided to just copy the mailer from old python based custom reporter into websafety-ui as a component; this will allow us to keep the ui separated from traffic reporter and still be able to verify the SMTP configuration provided by the admin.
