### ISSUE TITLE
Offensive users custom report failure

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#2192]
```
2024-01-06T08:20:01.737 ERR fatal error: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "user_id": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Traffic.Custom.Reporters.OffensiveUsersGenerator.Generate(SqliteConnection conn, Filters filters) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/OffensiveUsers.cs:line 66
   at Traffic.Custom.Reporters.OffensiveUsersReporter.BuildImpl(String outputDir, List`1 databases) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/OffensiveUsers.cs:line 155
   at Traffic.Custom.Reporters.BaseReporter.Build(String outputDir) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/BaseReporter.cs:line 55
   at Traffic.Custom.Reporters.BaseReporter.Generate(String outputDir) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/BaseReporter.cs:line 40
   at Traffic.Custom.Runner.Run(Args args) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Runner.cs:line 32
   at Traffic.Custom.Program.Main(String[] args) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Program.cs:line 28
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'near "user_id": syntax error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Traffic.Custom.Reporters.OffensiveUsersGenerator.Generate(SqliteConnection conn, Filters filters) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/OffensiveUsers.cs:line 66
   at Traffic.Custom.Reporters.OffensiveUsersReporter.BuildImpl(String outputDir, List`1 databases) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/OffensiveUsers.cs:line 155
   at Traffic.Custom.Reporters.BaseReporter.Build(String outputDir) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/BaseReporter.cs:line 55
   at Traffic.Custom.Reporters.BaseReporter.Generate(String outputDir) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Reporters/BaseReporter.cs:line 40
   at Traffic.Custom.Runner.Run(Args args) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Runner.cs:line 32
   at Traffic.Custom.Program.Main(String[] args) in /home/builder/diladele/websafety-ui/src.net/Traffic/Traffic.Custom/Program.cs:line 28
```

**Comment by ra-at-diladele-com** [comment]
fixed
