### ISSUE TITLE
FreeBSD - after install we cannot restart / reload from UI

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety#553]
```
Traceback (most recent call last):
  File "/opt/websafety/var/console/frame/views.py", line 68, in post
    profile.generate()
  File "/opt/websafety/var/console/frame/models.py", line 65, in generate
    self.archive()
  File "/opt/websafety/var/console/frame/models.py", line 114, in archive
    zipdir(etc_dir, zip_file)
  File "/opt/websafety/var/console/utility/zipdir.py", line 7, in zipdir
    initial_dir = os.getcwd()
OSError: [Errno 2] No such file or directory
```

**Comment by ra-at-diladele-com** [comment]
The reason for this is that ```The current directory may have been deleted by another process.``` - see https://stackoverflow.com/questions/3210902/python-why-does-os-getcwd-sometimes-crash-with-oserror.

Indeed this happens when we reinstall *without* restarting apache.

**Comment by ra-at-diladele-com** [comment]
FreeBSD support discontinued.
